<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PackageId>CodeWorks.Auth0Provider</PackageId>
    <Version>2.0.1</Version>
    <PackageTags>CodeWorks, Auth0, Identity, UserInfo</PackageTags>
    <Authors>Jake Overall, Mark Ohnsman</Authors>
    <Company>CodeWorks</Company>
    <Description>
      This library extends the HttpContext to provide a simple approach to get userInfo associated with a user account.
      
      HttpContext.GetUserInfoAsync()
      
      In startup you can configure your namespaced UserInfo Extensions based upon the rules setup in Auth0.
    </Description>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>
</Project>
